baseURL: "https://blog.yungen.studio"
title: Yungen's Blog
paginate: 8
theme: hugo-PaperMod
#enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: "G-4SRN3WZH2N"


params:
    env: production
    title: Yungen's Blog
    description: "My personal blog"
    author: Yungen
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'
  # home-info mode
    homeInfoParams:
        Title: "哈囉 \U0000270C"
        Content: >
            歡迎來到我的個人部落格
            
            - 我會在這裡分享一些我學習到的新知識
    socialIcons:
        - name: twitter
          url: "https://twitter.com/yungenlu"
        - name: github
          url: "https://github.com/yungen-lu"
        - name: linkedin
          url: "https://www.linkedin.com/in/yungen-lu-ba1073204/"

    #analytics:
     #   google:
      #      SiteVerificationTag: "XYZabc"
    cover:
        responsiveImages: false
taxonomies:
    category: categories
    tag: tags
    series: series
menu:
    main:
        - identifier: categories
          name: 分類
          url: /categories/
          weight: 10
        - identifier: tags
          name: 標籤
          url: /tags/
          weight: 20
        - identifier: Blog
          name: 首頁
          url: https://blog.yungen.studio
          weight: 30
