apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
  labels:
    app: myblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog
  template:
    metadata:
      labels:
        app: myblog
    spec:
      containers:
      - name: blog
        image: yungen/myblog:latest
        imagePullPolicy: "Always"
        ports:
        - name: myblog
          containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 150Mi